language: c

dist: trusty
sudo: false

git:
    depth: 9999999

install:
    - wget -q http://downloads.sourceforge.net/project/cunit/CUnit/2.1-3/CUnit-2.1-3-src.tar.bz2
    - tar jxf CUnit-2.1-3-src.tar.bz2
    - cd CUnit-2.1-3
    - ./configure --prefix=$(pwd)/install
    - make
    - make install
    - export CPPFLAGS=-I$(pwd)/install/include:$CPPFLAGS
    - export LDFLAGS=-L$(pwd)/install/lib:$LDFLAGS
    - cd ..

script: ./scripts/devbuild_ofp_odp_linux.sh
